'use client'

// scss
import './globals.scss';
// components
import SideBar from '@/components/sidebar/sidebar';
import Header from '@/components/header/header';
// hooks
import { usePathname } from 'next/navigation'
import { useEffect, useState } from "react";
import useScreenSize from './custom_hook/useScreenSize';
// framermotion
import { motion } from "framer-motion";

export default function RootLayout({ children }) {

  const pathname = usePathname();
  const screenSize = useScreenSize();

  // if screen width is less 999px so hidden sidebar and otherwise to vissible sidebar
  const screen_w_999px = '999';
  // if screen width is 768px so animate slow hidden and vissible main content-area
  const screen_w_768px = 768;

  // set screen size to open sidebar and close sidebar
  const [OpenSidebar, setOpenSidebar] = useState(
    screenSize.width > screen_w_999px ? true : false
  );

  const [visible, setVisible] = useState(false);

  useEffect(() => {
    // Set the component to be visible after a delay
    const timeoutId = setTimeout(() => {
      setVisible(true);
    }, 300);

    return () => clearTimeout(timeoutId); // Cleanup the timeout on component unmount
  }, []);


  return (
    <html lang="en">
      <body className={`overflow-hidden`}>

        {
          // route path === root so dont show sidebar just show signin or up form and other roots path to show sidebar & header
          pathname === '/' ? children
            :
            <div className={`body__wraper w-screen h-screen flex max-[${screen_w_999px}px]:overflow-hidden`}>

              {
                // if screen width is less 999px so hidden sidebar and otherwise to vissible sidebar
                visible ? <SideBar
                  class={`px-6 py-5 ${screenSize.width <= screen_w_999px && OpenSidebar === false ? 'hidden' : ''}`}
                  OpenSidebar={OpenSidebar} setOpenSidebar={setOpenSidebar}
                  winWidth={screenSize.width} screen_w_999px={screen_w_999px} screen_w_768px={screen_w_768px}
                /> : ''
              }

              {
                // if screen width is 768px so animate slow hidden and vissible main content-area
                visible ? <motion.div
                  initial={screenSize.width <= screen_w_768px && OpenSidebar === true ? { x: 100 } : ''}
                  animate={screenSize.width <= screen_w_768px && OpenSidebar === false ? { x: 0 } : ''}
                  transition={screenSize.width <= screen_w_768px && OpenSidebar === false ? { duration: 0.1 } : ''}
                  className={`main_area w-full overflow-x-hidden overflow-y-auto`} >

                  <Header OpenSidebar={OpenSidebar} setOpenSidebar={setOpenSidebar} />

                  {/* all nav pages are changed in this area and header and sidebar is constant */}
                  <div className="main_area_wrap h-full w-full">
                    {children}
                  </div>

                </motion.div> : ''
              }

            </div>
        }


      </body>
    </html>
  )
}





// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }